
import akshare as ak
import pandas as pd
import random
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import os
import platform
import requests
from datetime import datetime

# Configure Chinese Font
def get_chinese_font():
    system = platform.system()
    if system == "Windows":
        return "SimHei"
    elif system == "Darwin":
        return "Arial Unicode MS"  # or PingFang SC
    else:
        return "WenQuanYi Micro Hei"

plt.rcParams['font.sans-serif'] = [get_chinese_font()]
plt.rcParams['axes.unicode_minus'] = False


def _fetch_sector_flow_dataapi(sector_type):
    """通过 data.eastmoney.com 的中转接口获取板块资金流，规避 push2 连接问题。"""
    sector_code_map = {
        '行业资金流': 'm:90+t:2',
        '概念资金流': 'm:90+t:3',
        '地域资金流': 'm:90+t:1',
    }
    flow_key_map = {'今日': 'f62', '5日': 'f164', '10日': 'f174'}

    code = sector_code_map.get(sector_type)
    if not code:
        return None

    url = "https://data.eastmoney.com/dataapi/bkzj/getbkzj"
    params = {"key": flow_key_map['今日'], "code": code}
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
        )
    }
    resp = requests.get(url, params=params, headers=headers, timeout=15)
    resp.raise_for_status()
    payload = resp.json()

    if payload.get("rc") != 0:
        raise RuntimeError(f"DataAPI rc={payload.get('rc')}")

    diff = ((payload.get("data") or {}).get("diff") or [])
    if not diff:
        return None

    df = pd.DataFrame(diff)
    if "f14" not in df.columns or "f62" not in df.columns:
        return None

    df = df.rename(columns={"f14": "名称", "f62": "net_flow"})
    df["net_flow_billion"] = pd.to_numeric(df["net_flow"], errors="coerce") / 100000000
    df = df.dropna(subset=["net_flow_billion"])
    if df.empty:
        return None

    return df


def draw_sector_chart(inflow_df, outflow_df, name_col, flow_col, output_dir):
    """
    Draw a vertical 9:16 chart: Sector Power Bar (Inflow vs Outflow)
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    # Data Preparation
    # Top 10 Inflow (Red)
    top_in = inflow_df.head(10).copy()
    top_in = top_in.sort_values(by=flow_col, ascending=True) # Sort for horizontal bar (bottom to top)

    # Top 10 Outflow (Green)
    top_out = outflow_df.head(10).copy()
    top_out = top_out.sort_values(by=flow_col, ascending=False) # Sort for horizontal bar (top is largest negative)
    # Ensure outflow is negative for visualization direction if not already?
    # Usually flow_col is signed. Outflow should be negative.

    # Create Figure
    fig = plt.figure(figsize=(10, 17.7), facecolor='#1e1e1e')
    ax = fig.add_axes([0.1, 0.1, 0.8, 0.8])
    ax.set_facecolor('#1e1e1e')
    ax.axis('off')

    # Title
    date_str = datetime.now().strftime('%Y-%m-%d')
    fig.text(0.5, 0.95, f"板块资金流向大比拼 ({date_str})",
            ha='center', color='#FFD700', fontsize=24, fontweight='bold')

    # --- Top Panel: Inflow ---
    # 1. Inflow Chart (Top)
    ax_in = fig.add_axes([0.15, 0.55, 0.75, 0.35])
    ax_in.set_facecolor('#1e1e1e')
    ax_in.spines['top'].set_visible(False)
    ax_in.spines['right'].set_visible(False)
    ax_in.spines['bottom'].set_color('#555555')
    ax_in.spines['left'].set_color('#555555')

    bars_in = ax_in.barh(top_in[name_col], top_in[flow_col], color='#ff4d4d')
    ax_in.set_title("主力净流入 Top 10 (亿元)", color='white', fontsize=16, pad=10)
    ax_in.tick_params(axis='y', colors='white', labelsize=12)
    ax_in.tick_params(axis='x', colors='white')

    # Add labels
    for bar in bars_in:
        width = bar.get_width()
        ax_in.text(width + 0.1, bar.get_y() + bar.get_height()/2,
                   f'{width:.2f}', va='center', color='white', fontsize=10)

    # 2. Outflow Chart (Bottom)
    ax_out = fig.add_axes([0.15, 0.1, 0.75, 0.35])
    ax_out.set_facecolor('#1e1e1e')
    ax_out.spines['top'].set_visible(False)
    ax_out.spines['right'].set_visible(False)
    ax_out.spines['bottom'].set_color('#555555')
    ax_out.spines['left'].set_color('#555555')

    # Make outflow positive for bar length, but color green
    # Assuming flow_col is negative for outflow
    out_values = top_out[flow_col].abs()

    bars_out = ax_out.barh(top_out[name_col], out_values, color='#00cc66')
    ax_out.set_title("主力净流出 Top 10 (亿元)", color='white', fontsize=16, pad=10)
    ax_out.tick_params(axis='y', colors='white', labelsize=12)
    ax_out.tick_params(axis='x', colors='white')

    # Add labels (add negative sign back)
    for bar in bars_out:
        width = bar.get_width()
        ax_out.text(width + 0.1, bar.get_y() + bar.get_height()/2,
                   f'-{width:.2f}', va='center', color='white', fontsize=10)

    # Footer
    fig.text(0.5, 0.02, "Generated by Stock Daily Report", ha='center', color='#555555', fontsize=10)

    # DISABLED: User requested to disable sector_flow.png generation
    # output_path = os.path.join(output_dir, "sector_flow.png")
    # plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
    plt.close()
    # print(f"Sector Flow chart saved to {output_path}")


def get_sector_flow(sector_type='行业资金流'):
    """获取板块资金流排名 (返回 Top 10 流入和 Top 10 流出)"""
    try:
        print(f"正在获取 {sector_type} 数据...")
        import time
        df = None

        # Plan A: THS (Tonghuashun) - prioritized
        # Plan B: EastMoney (Fallback)

        data_source = "THS"

        # --- THS Implementation ---
        try:
            print(f"尝试数据源: 同花顺 (THS) - {sector_type}...")

            if sector_type == '概念资金流':
                # use Concept API
                df_ths = ak.stock_fund_flow_concept(symbol="即时")
                if df_ths is not None and not df_ths.empty:
                    # Cols: 序号, 行业, 行业指数, ..., 净额, ...
                    # Rename '行业' -> '名称', '净额' -> 'net_flow_billion' (Assuming Unit is Yi)
                    df_ths = df_ths.rename(columns={'行业': '名称', '净额': 'net_flow_billion'})

                    # Ensure numeric
                    df_ths['net_flow_billion'] = pd.to_numeric(df_ths['net_flow_billion'], errors='coerce')

                    # --- Filtering Noise (THS Concept) ---
                    exclude_keywords = [
                        "同花顺", "板块", "成分", "持股", "股通", "基金", "昨日", "人民币",
                        "融资", "融券", "B股", "ST", "转债", "高股息", "破净", "百元", "核心",
                        "龙头", "茅", "大盘", "中字头", "AH", "REITs", "ETF", "标准", "普尔", "MSCI", "含H股"
                    ]
                    if '名称' in df_ths.columns:
                         df_ths = df_ths[~df_ths['名称'].apply(lambda x: any(k in str(x) for k in exclude_keywords))]

                    top_inflow = df_ths.sort_values(by='net_flow_billion', ascending=False).head(10)
                    top_outflow = df_ths.sort_values(by='net_flow_billion', ascending=True).head(10)

                    return top_inflow, top_outflow, '名称', 'net_flow_billion'

            else:
                # Default / Industry API
                df_ths = ak.stock_board_industry_summary_ths()
                if df_ths is not None and not df_ths.empty:
                    # Columns: ['序号', '板块', '涨跌幅', '总成交量', '总成交额', '净流入', ...]
                    # Renaming for compatibility
                    df_ths = df_ths.rename(columns={'板块': '名称', '净流入': 'net_flow'})

                    # Assume 'net_flow' from THS is already in '亿' (Billions) based on debug.
                    df_ths['net_flow_billion'] = pd.to_numeric(df_ths['net_flow'], errors='coerce')

                    # --- Filtering Noise (THS Industry) ---
                    exclude_keywords = [
                        "同花顺", "板块", "成分", "持股", "股通", "基金", "昨日", "人民币",
                        "融资", "融券", "B股", "ST", "转债", "高股息", "破净", "百元", "核心",
                        "龙头", "茅", "大盘", "中字头", "AH", "REITs", "ETF", "标准", "普尔", "MSCI", "含H股"
                    ]
                    if '名称' in df_ths.columns:
                         df_ths = df_ths[~df_ths['名称'].apply(lambda x: any(k in str(x) for k in exclude_keywords))]

                    # Ensure we have both Inflow and Outflow
                    top_inflow = df_ths.sort_values(by='net_flow_billion', ascending=False).head(10)
                    top_outflow = df_ths.sort_values(by='net_flow_billion', ascending=True).head(10)

                    # Rename columns to match expected output for prompt generator
                    return top_inflow, top_outflow, '名称', 'net_flow_billion'

        except Exception as e:
            print(f"THS source failed: {e}")
            df_ths = None # Ensure df_ths is cleared if it failed

        # --- Fallback to EastMoney if THS fails ---
        print("尝试数据源: 东方财富 (EastMoney)...")
        df_em = None
        for i in range(2): # Reduced retries for EM
            try:
                df_em = ak.stock_sector_fund_flow_rank(indicator='今日', sector_type=sector_type)
                if df_em is not None and not df_em.empty:
                     data_source = "EM"
                     break
            except Exception as e:
                print(f"尝试 {i+1}/2 失败: {e}")
                time.sleep(1)

        if df_em is None or df_em.empty:
            print("尝试数据源: 东方财富 (DataAPI)...")
            try:
                df_dataapi = _fetch_sector_flow_dataapi(sector_type)
            except Exception as e:
                print(f"DataAPI source failed: {e}")
                df_dataapi = None

            if df_dataapi is None or df_dataapi.empty:
                print(f"❌ 最终获取 {sector_type} 失败 (THS/EM/DataAPI均失败)")
                return None

            # --- Filtering Noise / Garbage Names ---
            exclude_keywords = [
                "同花顺", "板块", "概念", "成分", "持股", "股通", "基金", "昨日", "人民币",
                "融资", "融券", "B股", "ST", "转债", "高股息", "破净", "百元", "核心",
                "龙头", "茅", "大盘", "中字头", "AH", "REITs", "ETF", "标准", "普尔", "MSCI"
            ]
            df_dataapi = df_dataapi[
                ~df_dataapi["名称"].apply(lambda x: any(k in str(x) for k in exclude_keywords))
            ]
            top_inflow = df_dataapi.sort_values(by='net_flow_billion', ascending=False).head(10)
            top_outflow = df_dataapi.sort_values(by='net_flow_billion', ascending=True).head(10)
            return top_inflow, top_outflow, '名称', 'net_flow_billion'

        # Process EastMoney data if it was successfully retrieved
        target_col = None
        name_col = None

        # 优先寻找 "主力净流入"
        for col in df_em.columns:
            if "主力" in col and "净流入" in col and "净额" in col:
                target_col = col
                break

        # Fallback
        if not target_col:
             for col in df_em.columns:
                if "净流入" in col and "净额" in col and "今日" in col:
                    target_col = col
                    break

        for col in df_em.columns:
             if "名称" in col:
                name_col = col
                break

        if not target_col or not name_col:
            print(f"❌ 东方财富数据列识别失败: target_col={target_col}, name_col={name_col}")
            return None

        # 确保数值类型
        df_em['net_flow_billion'] = pd.to_numeric(df_em[target_col], errors='coerce') / 100000000

        # --- Filtering Noise / Garbage Names ---
        exclude_keywords = [
            "同花顺", "板块", "概念", "成分", "持股", "股通", "基金", "昨日", "人民币",
            "融资", "融券", "B股", "ST", "转债", "高股息", "破净", "百元", "核心",
            "龙头", "茅", "大盘", "中字头", "AH", "REITs", "ETF", "标准", "普尔", "MSCI"
        ]

        # If we have name_col, filter
        df_em = df_em[~df_em[name_col].apply(lambda x: any(k in str(x) for k in exclude_keywords))]

        # 排序
        top_inflow = df_em.sort_values(by='net_flow_billion', ascending=False).head(10)
        top_outflow = df_em.sort_values(by='net_flow_billion', ascending=True).head(10)

        return top_inflow, top_outflow, name_col, 'net_flow_billion'

    except Exception as e:
        print(f"获取 {sector_type} 失败: {e}")
        return None


def get_creative_title(top_names):
    """根据Top板块生成生动标题"""
    if not top_names:
        return "资金涌入"

    # 1. 组合判断 (Combos)
    # 金融
    finance_kw = ['证券', '银行', '保险', '多元金融']
    fin_count = sum(1 for n in top_names if any(k in n for k in finance_kw))
    if fin_count >= 2:
        return random.choice(["大金融爆发", "金三胖发力", "权重搭台", "金融狂欢"])

    # 科技
    tech_kw = ['半导体', '软件', '计算机', '通信', '电子', '芯片', '光刻机', '消费电子']
    tech_count = sum(1 for n in top_names if any(k in n for k in tech_kw))
    if tech_count >= 2:
        return random.choice(["科技狂欢", "硬科技突围", "科创大涨", "算力崛起", "芯火燎原"])

    # 新能源
    new_energy_kw = ['光伏', '电池', '风电', '能源金属', '电网', '储能']
    ne_count = sum(1 for n in top_names if any(k in n for k in new_energy_kw))
    if ne_count >= 2:
        return random.choice(["新能车飙车", "绿电狂飙", "光储盛宴", "赛道股回归", "电光火石"])

    # 医药医疗
    med_kw = ['医药', '医疗', '中药', '生物制品', '化学制药']
    med_count = sum(1 for n in top_names if any(k in n for k in med_kw))
    if med_count >= 2:
        return random.choice(["医药反攻", "吃药行情", "杏林春暖", "大健康起舞"])

    # 消费
    con_kw = ['酿酒', '食品', '旅游', '家电', '零售', '商业百货']
    con_count = sum(1 for n in top_names if any(k in n for k in con_kw))
    if con_count >= 2:
        return random.choice(["大消费复苏", "喝酒吃肉", "消费回暖", "醉美A股"])

    # 2. Top 1 单一判断 (Top 1 Specific)
    first = top_names[0]

    mapping = {
        # 大金融
        "证券": ["牛市旗手", "券商暴动", "旗手扛鼎"],
        "银行": ["大象起舞", "定海神针", "银行护盘"],
        "保险": ["险资进场", "蓝筹核心"],
        "多元金融": ["金融活跃", "金控发力"],

        # 核心科技
        "半导体": ["芯火燎原", "国产之光", "缺芯涨价"],
        "芯片": ["芯火燎原", "国产之光"],
        "软件": ["软件定义", "信创崛起", "数字底座"],
        "计算机": ["算力为王", "AI风口", "数字经济"],
        "通信": ["5G先锋", "信息高速", "云网融合"],
        "电子": ["电子狂潮", "硬件复苏"],
        "消费电子": ["果链反弹", "消费复苏"],
        "光刻机": ["突破封锁", "光刻机魂"],
        "PCB": ["电子之母", "硬板崛起"],

        # 新能源/赛道
        "光伏": ["光芒万丈", "追光逐日", "光伏反转"],
        "电池": ["能动未来", "锂想主义", "电池革命"],
        "能源金属": ["锂钴齐飞", "资源为王"],
        "风电": ["御风而行", "风电抢装"],
        "电网": ["特高压起", "电网升级"],

        # 大消费
        "酿酒": ["把酒言欢", "醉美A股", "喝酒吃药"],
        "食品": ["舌尖美味", "吃喝行情"],
        "家电": ["智能家居", "家电下乡"],
        "旅游": ["诗与远方", "报复消费"],
        "航空": ["起飞时刻", "云端漫步"],
        "酒店": ["复苏先锋", "出行回暖"],
        "影视": ["票房大卖", "娱乐至上"],
        "游戏": ["玩赚世界", "元宇宙风口"],
        "汽车": ["极速狂飙", "弯道超车"],

        # 医药医疗
        "医药": ["药神归来", "健康中国"],
        "医疗": ["器械突围", "医疗新基建"],
        "中药": ["国粹传承", "中药瑰宝"],
        "生物": ["创新药魂", "生物科技"],

        # 周期/资源
        "石油": ["两桶油", "黑金狂舞"],
        "煤炭": ["煤飞色舞", "黑金时代"],
        "有色": ["有色王者", "顺周期"],
        "钢铁": ["钢铁洪流", "基建脊梁"],
        "化工": ["化工茅起", "涨价题材"],
        "黄金": ["金光闪闪", "避险之王"],
        "稀土": ["稀土永磁", "工业维生素"],

        # 地产基建
        "房地产": ["金辉重现", "地产反弹", "保交楼"],
        "工程建设": ["基建狂魔", "稳增长"],
        "水泥": ["建材龙头", "涨价预期"],
        "建材": ["地产链动", "装修旺季"],

        # 题材概念
        "低空经济": ["飞行汽车", "低空腾飞"],
        "人工智能": ["AI觉醒", "智领未来"],
        "机器人": ["人机共舞", "智能制造"],
        "卫星导航": ["星链计划", "天地互联"],
        "量子科技": ["量子纠缠", "未来科技"],
        "华为": ["遥遥领先", "鸿蒙生态"],
        "数字货币": ["数字人民币", "金融科技"],
    }

    # 模糊匹配
    for key, opts in mapping.items():
        if key in first:
            return random.choice(opts)

    # 3. 通用兜底 (Fallback)
    suffixes = ["领涨", "爆发", "抢筹", "崛起", "突围", "吸金", "霸榜", "大涨"]
    # 取板块名简写 (e.g. remove '行业')
    short_name = first.replace('行业', '').replace('概念', '').replace('板块', '')
    return f"{short_name}{random.choice(suffixes)}"


def generate_prompt(industry_inflow, industry_outflow, output_path="results/sector_flow_image_prompt.txt"):
    """
    Generate AI Prompt in Midjourney/SD format (Based on 20260204 template)
    """
    # Helper: Clean Name
    import re
    def clean_sector_name(raw_name):
        match = re.search(r'\((.*?)\)', raw_name)
        if match:
            inner = match.group(1).strip()
            if inner: return inner
        cleaned = raw_name.replace("概念", "").replace("板块", "").replace("行业", "")
        return cleaned.strip()

    # Creative Title
    top_names_for_title = list(industry_inflow.head(3)['名称'])
    selected_title = get_creative_title(top_names_for_title)

    # Get top 3 inflow for giants
    top3_in = industry_inflow.head(3)
    giant_entries = []
    for idx, (_, row) in enumerate(top3_in.iterrows()):
        val = float(row['net_flow_billion'])
        c_name = clean_sector_name(row['名称'])
        giant_entries.append((c_name, val))

    # Get top 10 outflow for worshippers
    top10_out = industry_outflow.head(10)
    worshipper_labels = []
    for _, row in top10_out.iterrows():
        val = float(row['net_flow_billion'])
        c_name = clean_sector_name(row['名称'])
        worshipper_labels.append(f"{c_name} ({val:.1f}亿)")

    # Prepare summary for content details
    top5_in = industry_inflow.head(5)
    top5_out = industry_outflow.head(5)

    inflow_summary = ", ".join([f"{i+1}. {clean_sector_name(row['名称'])} (+{row['net_flow_billion']:.1f}亿)"
                                 for i, (_, row) in enumerate(top5_in.iterrows())])
    outflow_summary = ", ".join([f"{i+1}. {clean_sector_name(row['名称'])} ({row['net_flow_billion']:.1f}亿)"
                                  for i, (_, row) in enumerate(top5_out.iterrows())])

    # Build the prompt in correct Midjourney/SD format
    prompt_content = f"""(masterpiece, best quality), (vertical:1.2), (aspect ratio: 10:16), (hand drawn), (illustration), (vintage style), (surrealism)

**SUBJECT**: A surreal conceptual illustration with CLEAR TEXT.

**HEADER TEXT**:
- At the top of the image, elegantly integrate the text "**{selected_title}**".
- **Font Style**: **Artistic Chinese Calligraphy** (But CLEAR and LEGIBLE).
- **BACKGROUND for Text**: Place the text on a **Red Ink Grunge** or **Paint Brush Stroke** background.
- **Text Color**: **Gold or White**, High Contrast for readability.

1. **THE GIANTS (Top Inflow Sectors)**:
   Three COLOSSAL, SYMBOLIC MONUMENTS towering in the center. (NON-HUMANOID)
   - **CENTER**: Object for **"{giant_entries[0][0]}"**. Label: "**{giant_entries[0][0]}**" (Black Bold Ink) & "+{giant_entries[0][1]:.1f}亿" (Red).
   - **LEFT**: Object for **"{giant_entries[1][0]}"**. Label: "**{giant_entries[1][0]}**" (Black Bold) & "+{giant_entries[1][1]:.1f}亿".
   - **RIGHT**: Object for **"{giant_entries[2][0]}"**. Label: "**{giant_entries[2][0]}**" (Black Bold) & "+{giant_entries[2][1]:.1f}亿".

2. **THE WORSHIPPERS (Top Outflow Sectors)**:
   In the **FOREGROUND**, a group of **LARGE** figures (pilgrims) with their backs facing the viewer.
   - **POSES**: **Varying kneeling and bowing poses**. Some slumped forward, some upright, some prostrate. **Chaotic and non-uniform arrangement**.
   - **BACK LABELS**: The text on their backs must be **LARGE, CLEAR and LEGIBLE**.
   - **Label Styling**: **Varying Font Sizes**. Larger losses should have **LARGER TEXT**.
   - **Labels**: {", ".join(worshipper_labels)}
   - **Style**: **Hand-written Style but Clean**.
   - **TEXT COLOR - Name**: **Bright Glowing White** (High Visibility).
   - **TEXT COLOR - Number**: **Light Green / Pastel Green** (Clear distinction).
   - **Text Quality**: (perfect text:1.4), (correct chinese characters:1.2).

**ART STYLE**:
- **Vintage Hand-drawn Illustration**: Warm paper texture background, ink lines, watercolor washes.
- **Atmosphere**: Epic, religious scale, slightly dystopian but artistic.
- **Colors**: Sepia, warm brown, faded red (giants), dull green/grey (worshippers).

(Optimized for Nano Banana Pro: Vintage Art Style + Clear Text enforcement)"""

    with open(output_path, "w", encoding='utf-8') as f:
        f.write(prompt_content.strip())

    print(f"✅ Image Prompt saved to {output_path} (Format: Midjourney/SD)")



def run(date_dir=None):
    """每日定期运行的入口函数"""
    print(f"\n=== A股板块资金流向统计 ({datetime.now().strftime('%Y-%m-%d')}) ===")

    # 1. 获取数据
    res_industry = get_sector_flow('行业资金流')
    res_concept = get_sector_flow('概念资金流')

    if res_industry or res_concept:
        # 2. 打印文本表格
        if res_industry:
            inflow, outflow, name_col, flow_col = res_industry
            print("\\n🏆 行业板块 - 主力净流入 Top 10")
            for i, (_, row) in enumerate(inflow.iterrows()):
                print(f"{i+1}. {row[name_col]:<10} {row[flow_col]:.2f}亿")

            print("\\n😭 行业板块 - 主力净流出 Top 10")
            for i, (_, row) in enumerate(outflow.iterrows()):
                print(f"{i+1}. {row[name_col]:<10} {row[flow_col]:.2f}亿")
        else:
             print("\\n⚠️ 行业资金流获取失败")

        if res_concept:
            print("\\n🏆 概念板块 - 主力净流入 Top 10")
            inflow_c, outflow_c, name_col_c, flow_col_c = res_concept
            for i, (_, row) in enumerate(inflow_c.iterrows()):
                print(f"{i+1}. {row[name_col_c]:<10} {row[flow_col_c]:.2f}亿")
        else:
            print("\\n⚠️ 概念资金流获取失败")

        # 3. 确定输出路径
        if date_dir:
            prompt_dir = os.path.join(date_dir, "AI提示词")
            if not os.path.exists(prompt_dir):
                os.makedirs(prompt_dir, exist_ok=True)
            prompt_path = os.path.join(prompt_dir, "资金流向_Prompt.txt")
        else:
            # 默认路径: 自动获取今日日期
            today_dir = datetime.now().strftime('%Y%m%d')
            prompt_dir = os.path.join("results", today_dir, "AI提示词")
            if not os.path.exists(prompt_dir):
                os.makedirs(prompt_dir, exist_ok=True)
            prompt_path = os.path.join(prompt_dir, "资金流向_Prompt.txt")

        # 4. 生成提示词 (Prioritize Industry data for "Real Sector" visualization)
        if res_industry:
             inflow, outflow, name_col, flow_col = res_industry

             # Draw the Chart
             if date_dir:
                 draw_sector_chart(inflow, outflow, name_col, flow_col, date_dir)
             else:
                 # Fallback to current date dir if not provided
                 today_dir = datetime.now().strftime('%Y%m%d')
                 out_dir = os.path.join("results", today_dir)
                 draw_sector_chart(inflow, outflow, name_col, flow_col, out_dir)

             generate_prompt(inflow, outflow, output_path=prompt_path)
             print("✅ 板块资金流分析已完成 (使用行业数据生成提示词)")
             # Also print fallback Concept if available? No, focus strictly on industry as primary.
             return True

        elif res_concept:
             # Use Concept data as fallback
             inflow_c, outflow_c, name_col_c, flow_col_c = res_concept

             # Draw the Chart (Concept)
             if date_dir:
                 draw_sector_chart(inflow_c, outflow_c, name_col_c, flow_col_c, date_dir)
             else:
                 today_dir = datetime.now().strftime('%Y%m%d')
                 out_dir = os.path.join("results", today_dir)
                 draw_sector_chart(inflow_c, outflow_c, name_col_c, flow_col_c, out_dir)

             generate_prompt(inflow_c, outflow_c, output_path=prompt_path)
             print("✅ 板块资金流分析已完成 (使用概念数据生成提示词)")
             return True

        return False
    else:
        print("⚠️ 数据(行业/概念)均获取失败，跳过板块分析")
        return False


if __name__ == "__main__":
    run()
